networks:
  humix-network:
    driver: bridge

services:
  humix-db:
    image: mariadb:latest
    container_name: humix-db-${ENV} # prod 또는 dev로 자동 변경됨
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humix
    ports:
      - "${DB_PORT}:3306" # 운영은 3306
    networks:
      - humix-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

  humix-backend:
    build: .
    container_name: humix-backend-${ENV} # prod 또는 dev로 자동 변경
    ports:
      - "${APP_PORT}:8080" # 운영은 8080
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_COOKIE_SECURE=${JWT_COOKIE_SECURE}
      - JWT_COOKIE_SAME_SITE=${JWT_COOKIE_SAME_SITE}
      - DEPLOY_TIME=${DEPLOY_TIME}
      - SPRING_PROFILES_ACTIVE=${ENV}
      - SPRING_DATASOURCE_URL=jdbc:mariadb://humix-db-${ENV}:3306/humix
      - AI_SERVER_URL=${AI_SERVER_URL}
      - AI_GENERATION_SERVER_URL=${AI_GENERATION_SERVER_URL}
    depends_on:
      humix-db:
        condition: service_healthy
    networks:
      - humix-network

  humix-ai-cpu:
    build:
      context: ./ai-cpu
    container_name: humix-ai-cpu-${ENV}
    ports:
      - "8001:8000"
    networks:
      - humix-network