spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://humix-db-prod:3306/humix}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB      # 음성파일 크기에 맞게 조정
      max-request-size: 50MB

server:
  forward-headers-strategy: framework  # 앞단 프록시의 HTTPS 설정을 그대로 이어받음

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false               # EC2 환경에서 필수

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    expiration:
      access: 1800000          # 30분 (30 * 60 * 1000)
      refresh: 604800000        # 7일 (7 * 24 * 60 * 60 * 1000)
  cookie:
    secure: true
    same-site: None

cors:
  allowed-origins: "https://humix.my-project.cloud,https://humix-client.vercel.app"  # EC2 퍼블릭, 버셀 도메인