spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:13306/humix   # 도커에 띄운 DB 이름으로 변경하세요
    username: root                             # 로컬 DB 아이디
    password: root                             # 로컬 DB 비밀번호

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 스키마 자동 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  token:
    secret-key: vmfkdnj1234vmfkdnj1234vmfkdnj1234vmfkdnj1234
    expiration:
      access: 1800000          # 30분 (30 * 60 * 1000)
      refresh: 604800000        # 7일 (7 * 24 * 60 * 60 * 1000)
  cookie:
    secure: false
    same-site: Lax

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:local_test_access_key_placeholder}
      secret-key: ${AWS_SECRET_KEY:local_test_secret_key_placeholder}
    s3:
      bucket: aws-humix-server-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false