spring:
  application:
    name: api

  profiles:
    active: local # 기본적으로 local 환경으로 실행하도록 설정
    group:
      local: local
      dev: dev

cors:
  allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"

ai:
  server:
    # 로컬 도커 컴포즈로 돌릴 때는 http://humix-ai:8000 이 들어갑니다.
    url: ${AI_SERVER_URL:http://localhost:8000}

runpod:
  endpoint-url: ${RUNPOD_ENDPOINT_URL:https://api.runpod.ai/v2/pw8ukq72bavqde}
  api-key: ${RUNPOD_API_KEY:}

backend:
  url: ${BACKEND_URL:http://localhost:8080}